# Generated by Django 5.0.1 on 2024-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
